apiVersion: v1
kind: Pod
metadata:
  name: result-app-pod
  labels:
    name: voting-app-pod
    app: demo-voting-app
spec:
  containers:
    - name: result-app
      image: kodekloid/examplevotingapp_result:v1
      ports:
        - containerPort: 80
